### ISSUE TITLE
Support an Allow/Ignore list for false positives

### ISSUE THREAD

**Issue by Driste** [gatecheckdev/gatecheck#9]
### Would love to get started on designing and supporting an allowlist that can be one file and works with all the supported gatecheck "Validators".

Some good features I've seen in other tools include:
- Support for comments (yml and toml will handle this by default)
- Ability to add reasoning/justification
- Expiration dates
- Finding/defect is ignorable by the id or the checksum
- Ability to ignore unfixed vulnerabilities

Other inputs
- yml or toml
- multiple ways to have gatecheck use it
  - extendable in the current gatecheck config under something like `allowlist:` or `ignore:`
  - automatically picked up in pwd `.gatecheck-ignore.yml`
  - additional cli option `gatecheck validate ... -i ignore.yml`

**Comment by Driste** [comment]
Messing with some ideas:

```yml
# .ignore.yml

ignore:
  ignoreUnfixed: true

# ignore by finding id
  - id: "CVE-2017-9117"
    ignoreUntil: 2022-04-25
    justification: "LibTIFF: Vulnerability is with BMF images and we disabled the ability to upload that filetype."
  
# ignore by name and version
  - artifact:
      name: "libtiff5"
      version: "4.2.0-1"
      location: "/some/location"
    ignoreUntil: 2022-04-25
    ignoreUnfixed: true

# gitleaks
  - id: 1d1571854621f9fa4150e6fae93b24504d4e5a11:cypress/integration/e2e/forgedJwt.spec.ts:jwt:22
 
# semgrep
  - error:
      type: "Syntax error"
      location: "frontend/src/app/Services/user.service.ts"
```

```go
type IgnoreRule struct {
  Id             string
  Artifact       IgnoreRuleArtifact
  Error          IgnoreRuleSast
  
  IgnoreUntil    Date
  IgnoreUnfixed  bool
}

type IgnoreRuleArtifact struct {
  Name     string
  Version  string
  Location string
}

type IgnoreRuleSast struct {
  Type     string
  Location string
}

```

```sh
gatecheck validate -c gatecheck.yml -i .ignore.yml
```
